Exception on /gene-operations/gene-suggest [GET]
Traceback (most recent call last):
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry[key]
KeyError: 139715456501504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/end_points/gene_operations.py", line 24, in get
    gene_suggestions = self.retrive_list_from_database(query, species, limit)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/end_points/gene_operations.py", line 35, in retrive_list_from_database
    gene_suggestions = gene.query.filter_by(species=species)	\
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 1012, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 3206, in __call__
    return self.class_(**local_kw)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 559, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 423, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/hossam/Documents/EBI/ebi-technical-test/1-REST/env/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
